name: CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build
      working-directory: moodify/moodify-client
      run: |
        touch .env
        echo REACT_APP_CLIENT_ID=${{ secrets.REACT_APP_CLIENT_ID }} >> .env
        echo REACT_APP_AUTHORIZE_URL=${{ secrets.REACT_APP_AUTHORIZE_URL }} >> .env
        echo REACT_APP_REDIRECT_URL=${{ secrets.REACT_APP_REDIRECT_URL }} >> .env
        npm run build
        npm run deploy