name: CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      working-directory: ./moodify-client
    - name: setup git config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
    - name: install
      run: |
        npm install
        touch .env
    - name: create env
      run: |
        echo REACT_APP_CLIENT_ID=${{ secrets.REACT_APP_CLIENT_ID }} >> .env
        echo REACT_APP_AUTHORIZE_URL=${{ secrets.REACT_APP_AUTHORIZE_URL }} >> .env
        echo REACT_APP_REDIRECT_URL=${{ secrets.REACT_APP_REDIRECT_URL }} >> .env
    - name: build and deploy
      run: |
        npm run build
        npm run deploy