name: CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Build
      run: |
        npm run build
        npm run deploy
      env: |
        REACT_APP_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }}
        REACT_APP_AUTHORIZE_URL: ${{ secrets.REACT_APP_AUTHORIZE_URL }}
        REACT_APP_REDIRECT_URL: ${{ secrets.REACT_APP_REDIRECT_URL }}