name: CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        npm install
        npm run build
      env: |
        REACT_APP_CLIENT_ID=${{ secrets.REACT_APP_CLIENT_ID }}
        REACT_APP_AUTHORIZE_URL=${{ secrets.REACT_APP_AUTHORIZE_URL }}
        REACT_APP_REDIRECT_URL=${{ secrets.REACT_APP_REDIRECT_URL }}

    - name: Deploy
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
